# Generated by Django 4.1.7 on 2024-02-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_topic_tweet_delete_comment_topic_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.tweet')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
