# Generated by Django 4.1.7 on 2024-02-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_comment_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('csv', models.FileField(null=True, upload_to='csv_files')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstfive', models.TextField()),
                ('negfive', models.TextField()),
                ('b_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
