# Generated by Django 4.1.7 on 2024-02-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_brand_comments_delete_comment_delete_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
